---
- name: ensure no packages will prevent the distribution update
  block:
    - name: check for damaged packages
      register: _dpkg_audit
      changed_when: false
      failed_when: false
      environment:
        LANGUAGE: en
        LANG: en_US.UTF-8
      ansible.builtin.command:
        cmd: dpkg --audit

    - name: check for hold packages
      register: _dpkg_hold
      changed_when: false
      failed_when: false
      environment:
        LANGUAGE: en
        LANG: en_US.UTF-8
      ansible.builtin.shell:
        cmd: dpkg --get-selections | grep hold

    - name: check dpkg audit and hold log
      when: >
        _dpkg_audit.stdout | length != 0
        or
        _dpkg_hold.stdout | length != 0
      block:
        - name: dpkg audit result
          when: _dpkg_audit.stdout | length != 0
          ansible.builtin.pause:
            seconds: 1
            prompt: |
              {{ _dpkg_audit.stdout }}

        - name: hold packages
          when: _dpkg_hold.stdout | length != 0
          ansible.builtin.pause:
            seconds: 1
            prompt: |
              {{ _dpkg_hold.stdout }}

        - name: cancel distribution update
          ansible.builtin.fail:
            msg: |
              distribution update aborted due to blocking packages

- name: prepare sources.list files for distribution update
  ansible.builtin.include_tasks: patch_files.yml
  vars:
    _from_release: "{{ ansible_distribution_release }}"
    _to_release: "{{ linux_patchday_distro_release }}"

- name: perform upgrade for distribution update
  ansible.builtin.include_tasks: upgrade.yml
