---
- name: update apt repo and cache
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true

- name: upgrade safe packages
  register: _apt_safe_upgrade
  until: _apt_safe_upgrade is succeeded
  retries: 2
  ansible.builtin.apt:
    upgrade: safe

- name: upgrade dist packages
  register: _apt_dist_upgrade
  until: _apt_dist_upgrade is succeeded
  retries: 2
  ansible.builtin.apt:
    upgrade: dist
    autoremove: true
    purge: true

- name: reboot if necessary
  ansible.builtin.include_tasks: reboot.yml
